# Generated by Django 6.0.2 on 2026-02-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'banner_advertising',
                'verbose_name_plural': 'banner_advertisings',
                'db_table': 'banner_advertising',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hourly_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='webinar',
            name='hosted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='ticket_expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='title_image',
            field=models.ImageField(null=True, upload_to='webinar_images/'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Category_Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.category')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('host', 'Host'), ('speaker', 'Speaker'), ('host_speaker', 'Host_speaker')], default='participant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webinar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.webinar')),
            ],
            options={
                'verbose_name': 'webinar_user',
                'verbose_name_plural': 'webinar_users',
                'db_table': 'webinar_user',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'webinar_id'), name='unique_webinar_user')],
            },
        ),
    ]
