# Generated by Django 6.0.2 on 2026-02-16 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_banner_advertising_category_hourly_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hourly_subscription',
            options={'ordering': ['created_at'], 'verbose_name': 'hourly_subscription', 'verbose_name_plural': 'hourly_subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='monthly_subscription',
            options={'ordering': ['created_at'], 'verbose_name': 'monthly_subscription', 'verbose_name_plural': 'monthly_subscriptions'},
        ),
        migrations.AddField(
            model_name='hourly_subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hourly_subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthly_subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthly_subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='hourly_subscription',
            table='hourly_subscription',
        ),
        migrations.AlterModelTable(
            name='monthly_subscription',
            table='monthly_subscription',
        ),
        migrations.AlterField(
            model_name='category_webinar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.type'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
