# Generated by Django 6.0.2 on 2026-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_hourly_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
