# Generated by Django 6.0.2 on 2026-02-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_webinar_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_webinar',
            options={'verbose_name': 'category_webinar', 'verbose_name_plural': 'category_webinars'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
        migrations.AlterModelTable(
            name='category_webinar',
            table='category_webinar',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
