# Generated by Django 6.0.2 on 2026-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_category_webinar_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar_user',
            name='role',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant'), ('HOST', 'Host'), ('SPEAKER', 'Speaker'), ('HOST_SPEAKER', 'Host_speaker')], default='PARTICIPANT', max_length=20),
        ),
    ]
