# Generated by Django 6.0.2 on 2026-02-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_webinar_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar_user',
            old_name='user_id',
            new_name='user_idd',
        ),
        migrations.RenameField(
            model_name='webinar_user',
            old_name='webinar_id',
            new_name='webinar_idd',
        ),
    ]
