# Generated by Django 6.0.2 on 2026-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_user_id_webinar_user_user_idd_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webinar_user',
            name='unique_webinar_user',
        ),
        migrations.AddConstraint(
            model_name='webinar_user',
            constraint=models.UniqueConstraint(fields=('user_idd', 'webinar_idd'), name='unique_webinar_user'),
        ),
    ]
