# Generated by Django 6.0.2 on 2026-02-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_webinar_user_unique_webinar_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webinar_user',
            name='unique_webinar_user',
        ),
        migrations.RenameField(
            model_name='webinar_user',
            old_name='user_idd',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='webinar_user',
            old_name='webinar_idd',
            new_name='webinar_id',
        ),
        migrations.AddConstraint(
            model_name='webinar_user',
            constraint=models.UniqueConstraint(fields=('user_id', 'webinar_id'), name='unique_webinar_user'),
        ),
    ]
