# Generated by Django 6.0.2 on 2026-02-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_remove_webinar_user_unique_webinar_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webinar_user',
            options={'verbose_name': 'webinar_user', 'verbose_name_plural': 'webinar_users'},
        ),
        migrations.RemoveField(
            model_name='webinar_user',
            name='created_at',
        ),
    ]
